Update JenkinsFile

diff --git a/JenkinsFile b/JenkinsFile
--- a/JenkinsFile
+++ b/JenkinsFile
@@ -5,8 +5,6 @@ pipeline {
         AWS_ACCESS_KEY_ID     = credentials('aws-creds')
         AWS_SECRET_ACCESS_KEY = credentials('aws-creds')
         AWS_DEFAULT_REGION    = 'ap-south-1'
-
-        GITHUB_CREDS = credentials('github-creds')
     }
 
     stages {
@@ -32,24 +30,29 @@ pipeline {
             }
         }
 
-stage('Commit static_inventory file into github') {
-    steps {
-        withCredentials([usernamePassword(
-            credentialsId: 'github-creds',
-            usernameVariable: 'GIT_USER',
-            passwordVariable: 'GIT_TOKEN'
-        )]) {
-            sh '''
-              git config user.email "patelbansi@gmail.com"
-              git config user.name "Bansil06"
-              git add static_inventory || true
-              git commit -m "static_inventory added by Jenkins" || true
-              git push https://${GIT_USER}:${GIT_TOKEN}@github.com/Bansil06/Jenkins-Terraform-Ansible.git HEAD:main
-            '''
-        }
-    }
-}
+        stage('Commit static_inventory file into github') {
+            steps {
+                withCredentials([usernamePassword(
+                    credentialsId: 'github-creds',
+                    usernameVariable: 'GIT_USER',
+                    passwordVariable: 'GIT_TOKEN'
+                )]) {
+                    sh '''
+                      git checkout main || git checkout -b main
+                      git config user.email "patelbansi@gmail.com"
+                      git config user.name "Bansil06"
 
+                      if [ -f static_inventory ]; then
+                        git add static_inventory
+                        git commit -m "static_inventory added by Jenkins" || true
+                        git push https://${GIT_USER}:${GIT_TOKEN}@github.com/Bansil06/Jenkins-Terraform-Ansible.git main
+                      else
+                        echo "static_inventory file not found, skipping commit"
+                      fi
+                    '''
+                }
+            }
+        }
 
         stage('Ansible - Install Docker on remote hosts') {
             agent { label 'ansible' }
